spring.application.name=innovatech
server.port=8089

# PARA LOGS MAS DETALLADOS
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web=TRACE

# USUARIO
spring.cloud.gateway.server.webmvc.routes[0].id=usuarios
spring.cloud.gateway.server.webmvc.routes[0].uri=http://usuarios:8083
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/usuarios/**

# RECURSOS HUMANOS Y PROYECTOS (ADMINISTRACIÓN DE PROYECTOS Y EMPLEADOS)
spring.cloud.gateway.server.webmvc.routes[1].id=recursos-humanos
spring.cloud.gateway.server.webmvc.routes[1].uri=http://recursos-humanos:8084
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/recursos-humanos/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=SetPath=/api/recursos-humanos

spring.cloud.gateway.server.webmvc.routes[2].id=proyectos
spring.cloud.gateway.server.webmvc.routes[2].uri=http://proyectos:8085
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/proyectos/**

# APIS CONSUMIDORAS DE EVENTOS DE KAFKA
spring.cloud.gateway.server.webmvc.routes[3].id=cuenta
spring.cloud.gateway.server.webmvc.routes[3].uri=http://cuenta:8086
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/cuenta/**

spring.cloud.gateway.server.webmvc.routes[4].id=analitica
spring.cloud.gateway.server.webmvc.routes[4].uri=http://analitica:8087
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/analitica/**

spring.cloud.gateway.server.webmvc.routes[5].id=alertas
spring.cloud.gateway.server.webmvc.routes[5].uri=http://alertas:8088
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/alertas/**