spring.application.name=innovatech
server.port=${PORT:8089}

# PARA LOGS MAS DETALLADOS
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web=TRACE

# USUARIO
spring.cloud.gateway.server.webmvc.routes[0].id=usuarios
spring.cloud.gateway.server.webmvc.routes[0].uri=https://api-usuario-somd.onrender.com
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/usuarios/**

# RECURSOS HUMANOS Y PROYECTOS (ADMINISTRACIÓN DE PROYECTOS Y EMPLEADOS)
spring.cloud.gateway.server.webmvc.routes[1].id=recursos-humanos
spring.cloud.gateway.server.webmvc.routes[1].uri=https://api-recursos-humanos.onrender.com
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/recursos-humanos/**

spring.cloud.gateway.server.webmvc.routes[2].id=proyectos
spring.cloud.gateway.server.webmvc.routes[2].uri=https://api-proyectos-ml4m.onrender.com
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/proyectos/**

# APIS CONSUMIDORAS DE EVENTOS DE KAFKA
spring.cloud.gateway.server.webmvc.routes[3].id=cuenta
spring.cloud.gateway.server.webmvc.routes[3].uri=https://api-cuenta.onrender.com
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/cuenta/**

spring.cloud.gateway.server.webmvc.routes[4].id=analitica
spring.cloud.gateway.server.webmvc.routes[4].uri=http://analitica:8087
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/analitica/**

spring.cloud.gateway.server.webmvc.routes[5].id=alertas
spring.cloud.gateway.server.webmvc.routes[5].uri=http://alertas:8088
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/alertas/**
